### PR TITLE
Add nodejs backend

### PR DESCRIPTION
**Pull request by maximest-pierre**
Not ready for merge. If merge it will break the current form.

### CODE REVIEW

**Comment by kauffj** [comment]
@billbitt now you have an express buddy

**Comment by billbitt** [comment]
woot woot!  yay express!

**Comment by billbitt** [comment]
the js contingency continues its slow ascent to power, lol @filipnyquist

**Comment by filipnyquist** [comment]
@billbitt this is what i call a slow revolution 😅

**Comment by tzarebczan** [comment]
@maximest-pierre what's the status on this PR?

**Pull request merged**
